[[main]]
none = "none"

[[main]]
name = "About"
pageRef = "about"
identifier = "AuxZTgyn05"
weight = 1

[[main]]
name = "Blog"
pageRef = "blog"
identifier = "34tDCy4sGL"
weight = 2

[[main]]
name = "Resume"
pageRef = "resume"
identifier = "wBE0FQbo3x"
weight = 3

[[main]]
name = "Contact Me"
pageRef = "contact"
identifier = "1ttkm21ydu"
weight = 4

[[main]]
pre = "github"
url = "https://github.com/Eonloop"
identifier = "YFhUlafrjK"
weight = 9999

[[main]]
pre = "linkedin"
url = "https://linkedin.com/in/ianj1993"
identifier = "nir8zxeQez"
weight = 9999

[[footer]]
none = "none"
